server:
  port: 10
  
spring:
  datasource:
    username: root
    password:
    url: jdbc:mariadb://localhost:3306/assignment


  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
